export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';
export const LOADING_CUSTOMERS = 'LOADING_CUSTOMERS';
export const CLEAR_CUSTOMERS = 'LOADING_CUSTOMERS';

export const GET_ADDRESSES = 'GET_ADDRESSES';
export const GET_ADDRESSES_ERROR = 'GET_ADDRESSES_ERROR';
export const LOADING_ADDRESSES = 'LOADING_ADDRESSES';
export const CLEAR_ADDRESSES = 'LOADING_ADDRESSES';

